#!/bin/bash
# Description: cross-shell prompt

# shellcheck disable=SC2220
while getopts ":i" arg; do
    case ${arg} in
    i)
        echo "Installing zoxide"
        # TODO: source common and use runst_install function
        cargo install starship
        # Use dconf to set font
        profile_id=$( eval "gsettings get org.gnome.Terminal.ProfilesList default" | tr -d "'")
        font="Hack NF 12"
        dconf write "/org/gnome/terminal/legacy/profiles:/:${profile_id}/font" "'$font'"
        # TODO: Download Nerd font
        mkdir -p ~/.config 
        _SCRIPT_DIR="$(dirname "$(readlink -f "$BASH_SOURCE")")"
        ln -sf "$_SCRIPT_DIR/../configs/starship.toml" ~/.config
        unset _SCRIPT_DIR
        ;;
    esac
done

case "$SHELL_NAME" in
bash)
    eval "$(starship init bash)"
    ;;
zsh)
    eval "$(starship init zsh)"
    ;;
fish)
    starship init fish | source
    ;;
esac
